### ISSUE TITLE
[BUG]:  Segmentation violation error during circuit computation in Goicicle

### ISSUE THREAD

**Issue by bigsky77** [ingonyama-zk/icicle#306]
## Description

I run the program with GPU acceleration in the [goicicle-example](https://github.com/bigsky77/goicicle-example/blob/master/main.go) and it crashes with a segmentation violation error.

### Reproduce

1. Go to goicicle-example on master.
2. Run with `go  run  --tags=icicle  main.go`

## Expected Behavior

The program should compute the circuit without crashing.

## Actual Result

Program crashed with `SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c99d3`.

**Error Message**:

```
09:01:48 INF compiling circuit
09:01:48 INF parsed circuit inputs nbPublic=1 nbSecret=1
09:01:48 INF building constraint builder nbConstraints=3
09:01:48 DBG precomputing proving key in GPU acceleration=icicle backend=groth16 curve=bn254 nbConstraints=3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c99d3]
```

```
goroutine 1 [running]:
github.com/consensys/gnark/backend/groth16/bn254.(*Proof).isValid(0x0)
        /home/simon/Ingonyama/gnark/backend/groth16/bn254/prove.go:52 +0x13
github.com/consensys/gnark/backend/groth16/bn254.Verify(0x0, 0xc00024ec00, {0xc000424000, 0x1, 0x1}, {0x0?, 0xa01860?, 0xc00041c018?})
        /home/simon/Ingonyama/gnark/backend/groth16/bn254/verify.go:61 +0x525
github.com/consensys/gnark/backend/groth16.Verify({0x9fe560?, 0x0?}, {0xa02040?, 0xc00024ec00?}, {0xa01860?, 0xc00041c060?}, {0x0, 0x0, 0x0})
        /home/simon/Ingonyama/gnark/backend/groth16/groth16.go:133 +0x1ec
main.main()
        /home/simon/Ingonyama/goicicle-example/main.go:49 +0x19c
exit status 2
```

## Environment

OS + Version: NixOS 23.11
Go Version: go1.21.5 
NVCC:  11.8
GPU type: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] (rev a1)

## Additional context

I think this may result from an incorrect Cuda header.

**Comment by bigsky77** [comment]
Update: 

Ran the program a few more times.  The program runs correctly 1/10ish times and outputs the following.

```
goicicle-example on  master [!?] via 🐹 v1.21.5 via ❄️  impure (cuda-env-shell-env) ❯ go run --tags=icicle main.go
09:54:37 INF compiling circuit
09:54:37 INF parsed circuit inputs nbPublic=1 nbSecret=1
09:54:37 INF building constraint builder nbConstraints=3
09:54:37 DBG precomputing proving key in GPU acceleration=icicle backend=groth16 curve=bn254 nbConstraints=3
09:54:37 INF setupDevicePointers position=start
09:54:37 DBG constraint system solver done nbConstraints=3 took=0.022538
09:54:37 DBG prover done acceleration=icicle backend=groth16 curve=bn254 nbConstraints=3 took=255.634608
09:54:37 DBG verifier done backend=groth16 curve=bn254 took=0.750893
```

The rest of the time I get the same error message.
